import { Geist, Geist_Mono, Roboto } from "next/font/google";
import {  Poppins } from 'next/font/google'
import "./globals.css";


const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const poppins = Poppins({ 
  subsets: ['latin'],
  weight:['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable:'--font-poppins'
  ,})

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

const GeIsRoboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${GeIsRoboto.variable}`}>
    <body className={`antialiased`}>
      {children}
    </body>
  </html>
  );
}
